# Generated by Django 5.0 on 2023-12-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Instructor', 'Instructor'), ('Manager', 'Manager')], default='student', max_length=20),
        ),
    ]
