# Generated by Django 5.0 on 2024-01-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_studentsonexams'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='questions',
            field=models.JSONField(default=list),
        ),
    ]
